export const PRIMARY_CHANGE = 'PRIMARY_CHANGE';
export const UPLOAD_INPROGRESS = 'UPLOAD_INPROGRESS';
export const UPLOAD_COMPLETE = 'UPLOAD_COMPLETE';
export const REMOVE_UPLOAD_MESSAGE = 'REMOVE_UPLOAD_MESSAGE';
